In [1]:
import numpy as np
import matplotlib
import pandas as pd
import matplotlib.pyplot as plt
import scipy
from scipy import io
from IPython import display
import time

In [3]:
data = io.loadmat('ex7faces.mat')
data.keys()

dict_keys(['__header__', '__version__', '__globals__', 'X'])

In [4]:
X = data['X']
X.shape

(5000, 1024)

In [6]:
# feature Normalization
m,n = X.shape
mu = np.mean(X, axis=0)
sigma = np.std(X, axis=0)
X_norm = (X-mu)/sigma

In [7]:
# PCA
convX = np.dot(X.T, X)/m
U, S, _ = np.linalg.svd(convX)

In [15]:
# PCA
K = 100
U_reduce = U[:,:K]
Z = np.dot(X_norm, U_reduce)
print(Z.shape)
Z[:10,:3]

(5000, 100)


array([[ 15.31451559,   2.79180747,   5.07286254],
       [ 10.1030899 ,  -2.50014999,  -3.02570512],
       [ -7.8661552 ,   1.22297262,  -6.17022211],
       [ 21.65058532,   1.7600141 ,  -1.71829408],
       [ 28.62231264,   4.48641632,  -8.35737846],
       [-12.70793722,  -0.87790968,   2.30044091],
       [ -6.91229661,  -3.30925306,  -1.91314525],
       [-11.11200911,  -0.74193724,   8.59898697],
       [  7.03273191,   5.35298246,   3.37434511],
       [  6.80622144,  -7.47985861, -16.2995379 ]])

In [18]:
# recover
X_approx = np.dot(Z, U_reduce.T)
print(X_approx[:10,:3])
print(X_norm[:10,:3])

[[-0.37774675 -0.39737429 -0.41712684]
 [ 0.38329792  0.37201758  0.30659438]
 [-0.30303515 -0.28643855 -0.19626688]
 [-0.70627335 -0.73397728 -0.63199942]
 [ 0.32520693  0.42018056  0.51801273]
 [ 1.70552663  1.63381848  1.52161631]
 [ 0.68046217  0.75784716  0.91014461]
 [-1.62160957 -1.55211933 -1.4534507 ]
 [ 0.17200363  0.11224846  0.05620317]
 [ 0.97187384  0.90104939  0.80970931]]
[[-0.31524019 -0.49758248 -0.69058357]
 [ 0.58400504  0.39602142  0.21916434]
 [-0.21749614 -0.27914597 -0.34690103]
 [-1.23403423 -0.8748819  -0.56928385]
 [ 0.46671219  0.53502647  0.50219702]
 [ 1.60054313  1.56763541  1.61411113]
 [ 0.17348004  0.63431579  1.00761252]
 [-1.11674138 -1.25218132 -1.35773204]
 [ 0.58400504  0.27687423 -0.38733427]
 [ 0.89678599  0.89246803  0.86609618]]
